# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import ez_setup
ez_setup.use_setuptools()

import sys
from setuptools import setup

main='scramble/main.py'
APP = ['scramble/main.py']
DATA_FILES = ['html', 'js']

if sys.platform == 'darwin':
    extra_options = dict(
        setup_requires=['py2app'],
        app=[main],
        # Cross-platform applications generally expect sys.argv to
        # be used for opening files.
        options=dict(py2app=dict(argv_emulation=True)),
    )
elif sys.platform == 'win32':
    extra_options = dict(
        setup_requires=['py2exe'],
        app=[main],
    )
else:
     extra_options = dict(
         scripts=[main],
     )

VERSION = "0.0.0"
with open('scramble/__version.py') as version_file:
	version_info = version_file.readlines()
VERSION = version_info[0].split('=')[-1]
APP_NAME = 'Scramble'

extra_options['plist'] = {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "GSU Scramble Research Project",
        'CFBundleIdentifier': "com.ramonat.scramble",
        'CFBundleVersion': VERSION,
        'CFBundleShortVersionString': VERSION,
        'NSHumanReadableCopyright': u"Copyright © 2015, Ramonat, All Rights Reserved",
        'LSPrefersPPC': True,
    }

setup(
    name=APP_NAME,
    data_files=DATA_FILES,
    version=VERSION.replace("'", ""),
    **extra_options
)
